Add all Custom Crafting classes and Tables
TheValarProject/AwakenDreamsClient pull request #37
Opened 2017-05-21 22:52 UTC by MartyParty21

Here it is, as promised. There is a lot of thing that could have been done better, for instance Ive made a lot of possibly unnecessary classes (all the Slot//Workbenches and Containers, Guis..), but I didnt want to loose any more time on thinking how to do it. So I lost a lot of time on rewriting the classes...
However, this works. The Crafting Tables are differentiated by meta and have same ID. Each has its own container and CraftingManager tho. Only thing needed to do are all the models, textures and Guis. I set everything to look like Elven Crafting Table for now, so it looks somehow.

You can check the 6998dc8 commit to see my first version. Thats with different ID's, and its just a start. It would work in the very same way. But the same ID, latest commit is sufficient and better in my opinion.

Have a look and tell me what you think. Feel free to add some code-saving edits to solve this multi-class madness (just a question of line saving and better feeling. Everything works well as it is, so we can leave it), or anything you like!

2017-05-27 06:54 UTC, scribblemaniac requested changes
Great stuff! It all seems to work well so far. There are a few sections that I think can be refactored to work and look a bit better and there are a few other things I want to talk about (don't worry nothing bad 😉 ) so when you get a chance and see me online, send me a message on Discord and we can discuss things further.

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/assets/minecraft/models/item/custom_crafting_table.json
> +    "parent": "block/custom_crafting_table"
Is this file even used? If yes, then `block/custom_crafting_table` doesn't seem to exist. If no, then we can just delete it.

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/block/BlockCustomWorkbench.java
> +            return new TextComponentTranslation("tile.customWorkbench.elven.name", new Object[0]);
I'm not sure where if anywhere this is used, but it doesn't seem right to leave it hard-coded to the elven workbench. Can we do something like `"tile.customWorkbench." + BlockCustomWorkbench.getUnlocalizedName(world.getBlockState(position)) + ".name"` with the getUnlocalizedName function as:
```
public static String getUnlocalizedName(IBlockState state)
{
    return ((BlockCustomWorkbench.EnumType)state.getValue(TYPE)).getUnlocalizedName();
}
```

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/client/gui/inventory/GuiRohirrimCrafting.java
> +	private static final ResourceLocation ROHIRRIM_CRAFTING_TABLE_GUI_TEXTURES = new ResourceLocation("textures/gui/container/crafting_table.png");
Do you think that there will be any differences between the GuiXCrafting aside from the background texture and font color? If we're not going to customize them any more than that, they we can probably get away with a single class that passes those two things into the constructor.

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/inventory/ContainerGoblinWorkbench.java
> +        this.craftResult.setInventorySlotContents(0, GoblinCraftingManager.getInstance().findMatchingRecipe(this.craftMatrix, this.worldObj));
Is this and the result slot type the only differences between all of the ContainerXWorkbench classes? Do you expect we'll need custom classes for other reasons?

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/inventory/SlotGoblinCrafting.java
> +        ItemStack[] aitemstack = GoblinCraftingManager.getInstance().getRemainingItems(this.craftMatrix, playerIn.worldObj);
Is this the only reason we need custom slots? Can you think of any other reason we would need custom slots in the future?

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/item/crafting/GoblinCraftingManager.java
> +    public ShapedRecipes addRecipe(ItemStack stack, Object... recipeComponents)
Can we have a parent `CustomCraftingManager` class which contains all of these reused functions in XCraftingManager?

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/item/crafting/RecipesCustom.java
> +		manager.addShapelessRecipe(new ItemStack(Items.THROWING_STONE, 4), new Object[] {Blocks.COBBLESTONE});
This recipe doesn't seem to be working for me, but the pipe does. Can you replicate this? There may be something wrong with `addShapelessRecipe`

2017-05-27 06:54 UTC, scribblemaniac commented on mcp/src/minecraft/net/minecraft/block/Block.java
> +        Block block500 = (new BlockCustomWorkbench()).setSoundType(SoundType.WOOD).setHardness(0.8F).setUnlocalizedName("customWorkbench");
Any particular reason why you chose to use two lines here? Or why the 786th block is named block500 😝

2017-05-30 14:40 UTC, MartyParty21 commented on mcp/src/minecraft/assets/minecraft/models/item/custom_crafting_table.json
> +    "parent": "block/custom_crafting_table"
It is not used, I just used it for testing. Thanks for discovery!

2017-05-30 15:06 UTC, MartyParty21 commented on mcp/src/minecraft/com/elementfx/tvp/ad/block/BlockCustomWorkbench.java
> +            return new TextComponentTranslation("tile.customWorkbench.elven.name", new Object[0]);
You are correct. I forgot to change this also. The method itself is called when the block is right-clicked it seems. Your suggestion works just fine to solve this. 
By the way the original getUnlocalizedName method from Block.java is never overwritten. Does it mean that whenever that method is called, it returns "customWorkbench" string? And is it even needed? Only use of unlocalizedName I know about is to set the name in .lang files. And that works, if I understand corectly, thanks to this getDisplayName method.

2017-05-30 15:14 UTC, MartyParty21 commented on mcp/src/minecraft/com/elementfx/tvp/ad/client/gui/inventory/GuiRohirrimCrafting.java
> +	private static final ResourceLocation ROHIRRIM_CRAFTING_TABLE_GUI_TEXTURES = new ResourceLocation("textures/gui/container/crafting_table.png");
No other diferences for sure. It should be alright with the constructors, I just wasnt sure with all the classes, and didnt want to connect them really together with constructors etc before you approve the system) I'll do it. I'll try my best with other classes as well, I wasnt too sure how to handle Crafting managers for instance, but your idea further below seems nice!

2017-06-08 20:00 UTC, MartyParty21 commented on mcp/src/minecraft/com/elementfx/tvp/ad/item/crafting/RecipesCustom.java
> +		manager.addShapelessRecipe(new ItemStack(Items.THROWING_STONE, 4), new Object[] {Blocks.COBBLESTONE});
The recipe works for me well, did u use cobblestone?

2017-06-08 20:02 UTC, MartyParty21 commented on mcp/src/minecraft/net/minecraft/block/Block.java
> +        Block block500 = (new BlockCustomWorkbench()).setSoundType(SoundType.WOOD).setHardness(0.8F).setUnlocalizedName("customWorkbench");
All vanilla blocks which have subblocks used this :smile: but it doesnt seem to make any difference...

2017-06-21 19:47 UTC, scribblemaniac commented on mcp/src/minecraft/com/elementfx/tvp/ad/item/crafting/RecipesCustom.java
> +		manager.addShapelessRecipe(new ItemStack(Items.THROWING_STONE, 4), new Object[] {Blocks.COBBLESTONE});
Oops, it seems I accidentally grabbed the Cobblestone Monster Egg block instead 🤦‍♂️. Works now.

2017-06-21 20:02 UTC, merged

2017-06-21 20:04 UTC, scribblemaniac commented
Merged! Thanks so much for your work and patience 😁